### ISSUE TITLE
Account for special booster packs

### ISSUE THREAD

**Issue by cman131** [cman131/last-season-received-criticism-for-not-happening-in-a-prison-but-it-turns-out-society-is-the-prison#3]
# Todo List
- [x] Innistrad + Dark Ascension - Replace common with double-faced card of any rarity
- [x] Shadows over Innistrad + Eldritch Moon - one common slot is replaced by a common or uncommon double-faced card. And 1/8 chance of an additional common slot being a rare or mythic double-faced card.
- [ ] War of the spark - each booster contains exactly one planeswalker card.
- [ ] Dominaria - each booster contains exactly one legendary creature.
- [x] Modern Horizons/Coldsnap - lands are replaced with snow-covered versions
- [x] Ice Age/Alliances - basic lands could be normal or snow-covered (10 options)
- [x] Oath of the gatewatch - Wastes take the land slot. No other basics
- [ ] Amonkhet/Hour of devastation, Battle for Zendikar/Oath of the gatewatch, Khaladesh/Aether Revolt - Expeditions, Inventions, Invocations. Takes the foil slot (same chance) just add it to the list of potential foils.
- [x] Journey to nyx - 1/1080 chance of a god pack containing all 15 gods and a land

# How to guide

If you want to create one, make a new file `{setCode}.js` in the `server/routes/booster-generation/sets` folder of the special set you want to handle replacing `{setCode}` with the actual 3 character expansion code of the set.

Model the new file after `server\routes\booster-generation\sets\set-template.js`
and fill out the generatePacks function to return an array of mapped booster packs.

| Parameter name  | Description |
| ------------- | ------------- |
| `cards` | An array of scryfall api card objects from the set without basic lands |
| `count` | A number indicating how many booster packs to generate |
| `lands` | An array of the 5 basic land scryfall objects [Plains, Forest, Island, Swamp, Mountain] |
| `mapCard` | A card mapping function that trims down and renames properties. Use this on the resulting cards when you put them in the booster pack. |
